package canonicalize

import (
	"fmt"
	"net"
	"net/url"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/net/idna"
)

// Elements whose text content is NEVER part of the signed content. These are
// either metadata (meta, link, script, style) or the signed-section wrapper's
// own metadata (meta tags inside a signed-section carry claims, not content).
// They are stripped entirely (with their contents) before extracting text.
//
// Go's RE2 has no backreferences, so we compile one non-greedy regex per
// element name and apply them in sequence.
var excludedPairTagNames = []string{"script", "style", "meta", "link", "head", "noscript"}

var excludedPairREs = func() []*regexp.Regexp {
	out := make([]*regexp.Regexp, 0, len(excludedPairTagNames))
	for _, name := range excludedPairTagNames {
		out = append(out, regexp.MustCompile(`(?is)<`+name+`\b[^>]*>.*?</`+name+`\s*>`))
	}
	return out
}()

// Self-closing and void elements (no text content) to strip.
var voidElementsRE = regexp.MustCompile(
	`(?i)<(meta|link|br|hr|img|input|source|track|wbr|area|base|col|embed|param)\b[^>]*/?>`,
)

// Boundary-producing elements from the protocol draft. A boundary-producing
// element emits a line feed after its descendants have contributed text.
const blockElements = `address|article|aside|blockquote|details|dialog|div|dl|` +
	`fieldset|figcaption|figure|footer|form|h[1-6]|header|hgroup|hr|li|main|nav|` +
	`ol|p|pre|section|table|td|th|tr|ul`

var (
	htmlTokenRE = regexp.MustCompile(`(?is)<!--[\s\S]*?-->|<![^>]*>|</?[a-z][a-z0-9-]*(?:\s[^<>]*)?\s*/?>`)
	tagNameRE   = regexp.MustCompile(`(?i)^</?\s*([a-z][a-z0-9-]*)`)
	attrBodyRE  = regexp.MustCompile(`(?i)^</?\s*[a-z][a-z0-9-]*`)
	attrRE      = regexp.MustCompile("([^\\s\"'<>/=]+)(?:\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s\"'=<>`]+)))?")
	blockNameRE = regexp.MustCompile(`(?i)^(` + blockElements + `)$`)
)

var signedAttrs = []string{"href", "src", "alt", "aria-label"}

var voidTags = map[string]bool{
	"area": true, "base": true, "br": true, "col": true, "embed": true,
	"hr": true, "img": true, "input": true, "link": true, "meta": true,
	"param": true, "source": true, "track": true, "wbr": true,
}

var excludedTags = map[string]bool{
	"script": true, "style": true, "template": true, "noscript": true,
	"iframe": true, "head": true, "meta": true, "link": true,
}

// namedEntities (the full HTML5 named-reference table) is defined in
// entities_gen.go, generated by tools/gen-entities.py. Lookups are
// case-sensitive per the HTML Living Standard.

var (
	namedEntityRE   = regexp.MustCompile(`&[a-zA-Z][a-zA-Z0-9]*;`)
	decimalEntityRE = regexp.MustCompile(`&#([0-9]+);`)
	hexEntityRE     = regexp.MustCompile(`&#[xX]([0-9a-fA-F]+);`)
)

// c1Replacements maps numeric references in the C1 range (0x80-0x9F) via the
// windows-1252 table, per the HTML5 "numeric character reference end" state.
var c1Replacements = map[rune]rune{
	0x80: 0x20AC, 0x82: 0x201A, 0x83: 0x0192, 0x84: 0x201E, 0x85: 0x2026,
	0x86: 0x2020, 0x87: 0x2021, 0x88: 0x02C6, 0x89: 0x2030, 0x8A: 0x0160,
	0x8B: 0x2039, 0x8C: 0x0152, 0x8E: 0x017D, 0x91: 0x2018, 0x92: 0x2019,
	0x93: 0x201C, 0x94: 0x201D, 0x95: 0x2022, 0x96: 0x2013, 0x97: 0x2014,
	0x98: 0x02DC, 0x99: 0x2122, 0x9A: 0x0161, 0x9B: 0x203A, 0x9C: 0x0153,
	0x9E: 0x017E, 0x9F: 0x0178,
}

// numericCharRef applies the HTML5 rules for a parsed numeric reference:
// null/out-of-range/surrogate collapse to U+FFFD; C1 controls map via
// windows-1252; everything else is the literal code point.
func numericCharRef(n int64) string {
	if n == 0 || n > 0x10FFFF || (n >= 0xD800 && n <= 0xDFFF) {
		return "\uFFFD"
	}
	if r, ok := c1Replacements[rune(n)]; ok {
		return string(r)
	}
	return string(rune(n))
}

func decodeEntities(text string) string {
	text = namedEntityRE.ReplaceAllStringFunc(text, func(match string) string {
		if v, ok := namedEntities[match]; ok {
			return v
		}
		return match
	})
	text = decimalEntityRE.ReplaceAllStringFunc(text, func(match string) string {
		m := decimalEntityRE.FindStringSubmatch(match)
		n, err := strconv.ParseInt(m[1], 10, 64)
		if err != nil {
			return "\uFFFD"
		}
		return numericCharRef(n)
	})
	text = hexEntityRE.ReplaceAllStringFunc(text, func(match string) string {
		m := hexEntityRE.FindStringSubmatch(match)
		n, err := strconv.ParseInt(m[1], 16, 64)
		if err != nil {
			return "\uFFFD"
		}
		return numericCharRef(n)
	})
	return text
}

// ExtractCanonicalText extracts canonical content from an HTML fragment for
// signing or verification. Mirrors the JS extractCanonicalText() reference
// implementation: strips excluded elements, emits signed semantic attribute
// records for href/src/alt/aria-label, converts boundary-producing elements
// to line feeds, decodes entities, and runs the full text normalization
// pipeline. The returned string is trimmed.
func ExtractCanonicalText(html string, opts ...Options) (string, error) {
	var o Options
	if len(opts) > 0 {
		o = opts[0]
	}
	base, err := parseBaseURL(o.BaseURL)
	if err != nil {
		return "", err
	}

	var parts []string
	index := 0
	excludedDepth := 0
	matches := htmlTokenRE.FindAllStringIndex(html, -1)
	for _, loc := range matches {
		if loc[0] > index && excludedDepth == 0 {
			appendCanonicalPart(&parts, NormalizeText(decodeEntities(html[index:loc[0]]), o))
		}
		token := html[loc[0]:loc[1]]
		index = loc[1]

		nameMatch := tagNameRE.FindStringSubmatch(token)
		if len(nameMatch) < 2 {
			continue
		}
		name := strings.ToLower(nameMatch[1])
		closing := strings.HasPrefix(strings.TrimSpace(token), "</")
		selfClosing := strings.HasSuffix(strings.TrimSpace(token), "/>") || voidTags[name]
		excluded := excludedTags[name]

		if closing {
			if excluded && excludedDepth > 0 {
				excludedDepth--
				continue
			}
			if excludedDepth > 0 {
				continue
			}
			if blockNameRE.MatchString(name) {
				appendCanonicalPart(&parts, "\n")
			}
			continue
		}

		if excluded {
			if !selfClosing {
				excludedDepth++
			}
			continue
		}
		if excludedDepth > 0 {
			continue
		}

		attrs := parseAttributes(token)
		if err := appendAttributeRecords(&parts, name, attrs, base); err != nil {
			return "", err
		}
		if name == "br" {
			appendCanonicalPart(&parts, "\n")
		}
		if selfClosing && blockNameRE.MatchString(name) {
			appendCanonicalPart(&parts, "\n")
		}
	}
	if index < len(html) && excludedDepth == 0 {
		appendCanonicalPart(&parts, NormalizeText(decodeEntities(html[index:]), o))
	}
	return finalizeCanonicalParts(parts), nil
}

// CanonicalizeClaims serializes a claims map as sorted "name:content\n"
// records. Both names and values are pushed through NormalizeText before
// serialization so the output is independent of trivial Unicode noise.
// Mirrors the JS canonicalizeClaims() reference implementation.
func CanonicalizeClaims(claims map[string]string) string {
	s, _ := CanonicalizeClaimsStrict(claims)
	return s
}

// CanonicalizeClaimsStrict is like CanonicalizeClaims but enforces the draft's
// MUST-fail rules: an empty normalized name is "claim-malformed", and two
// names that normalize to the same value are "claim-duplicate". Names are
// sorted by their UTF-8 byte sequence.
func CanonicalizeClaimsStrict(claims map[string]string) (string, error) {
	type entry struct{ name, value string }
	entries := make([]entry, 0, len(claims))
	seen := make(map[string]bool, len(claims))
	for k, v := range claims {
		name := strings.TrimSpace(NormalizeText(k))
		value := strings.TrimSpace(NormalizeText(v))
		if name == "" {
			return "", fmt.Errorf("claim-malformed")
		}
		if seen[name] {
			return "", fmt.Errorf("claim-duplicate")
		}
		seen[name] = true
		entries = append(entries, entry{name, value})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	var b strings.Builder
	for _, e := range entries {
		b.WriteString(e.name)
		b.WriteByte(':')
		b.WriteString(e.value)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func appendCanonicalPart(parts *[]string, value string) {
	if value == "" {
		return
	}
	*parts = append(*parts, value)
}

func finalizeCanonicalParts(parts []string) string {
	text := strings.Join(parts, "")
	for strings.Contains(text, "  ") {
		text = strings.ReplaceAll(text, "  ", " ")
	}
	text = regexp.MustCompile(`[ \t]*\n[ \t]*`).ReplaceAllString(text, "\n")
	for strings.Contains(text, "\n\n") {
		text = strings.ReplaceAll(text, "\n\n", "\n")
	}
	return strings.Trim(text, " \n")
}

func parseAttributes(token string) map[string]string {
	body := attrBodyRE.ReplaceAllString(token, "")
	body = strings.TrimSuffix(strings.TrimSpace(body), ">")
	body = strings.TrimSuffix(strings.TrimSpace(body), "/")
	attrs := map[string]string{}
	for _, m := range attrRE.FindAllStringSubmatch(body, -1) {
		if len(m) == 0 || m[1] == "" {
			continue
		}
		value := ""
		for _, candidate := range m[2:] {
			if candidate != "" {
				value = candidate
				break
			}
		}
		attrs[strings.ToLower(m[1])] = decodeEntities(value)
	}
	return attrs
}

func appendAttributeRecords(parts *[]string, elementName string, attrs map[string]string, base *url.URL) error {
	for _, attrName := range signedAttrs {
		raw, ok := attrs[attrName]
		if !ok {
			continue
		}
		value := raw
		if attrName == "href" || attrName == "src" {
			if base == nil && !hasURLScheme(value) {
				// Relative URL with no base cannot be resolved. The draft
				// (§4.3.2) requires a hard failure rather than a silent skip.
				return fmt.Errorf("attribute-canonicalization-failed: %s.%s: relative URL with no base", elementName, attrName)
			}
			normalized, err := normalizeURLAttribute(value, base)
			if err != nil {
				return fmt.Errorf("attribute-canonicalization-failed: %s.%s: %w", elementName, attrName, err)
			}
			value = normalized
		} else {
			value = strings.TrimSpace(NormalizeText(value))
		}
		if strings.ContainsRune(value, '\n') {
			return fmt.Errorf("attribute-canonicalization-failed: %s.%s contains newline", elementName, attrName)
		}
		if len(*parts) > 0 {
			last := (*parts)[len(*parts)-1]
			if last != "" && !strings.HasSuffix(last, " ") && !strings.HasSuffix(last, "\n") {
				*parts = append(*parts, "\n")
			}
		}
		*parts = append(*parts, "@attr:"+elementName+":"+attrName+":"+value+"\n")
	}
	return nil
}

func parseBaseURL(raw string) (*url.URL, error) {
	if raw == "" {
		return nil, nil
	}
	base, err := url.Parse(raw)
	if err != nil {
		return nil, err
	}
	if !base.IsAbs() || base.Host == "" {
		return nil, fmt.Errorf("base URL must be absolute")
	}
	return base, nil
}

func hasURLScheme(raw string) bool {
	i := strings.IndexByte(raw, ':')
	if i <= 0 {
		return false
	}
	for _, r := range raw[:i] {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '+' || r == '-' || r == '.' {
			continue
		}
		return false
	}
	return true
}

// removeDotSegments implements RFC 3986 §5.2.4, matching the WHATWG URL path
// normalization the reference JS/Rust bindings perform via `new URL`.
func removeDotSegments(path string) string {
	out := ""
	in := path
	for len(in) > 0 {
		switch {
		case strings.HasPrefix(in, "../"):
			in = in[3:]
		case strings.HasPrefix(in, "./"):
			in = in[2:]
		case strings.HasPrefix(in, "/./"):
			in = "/" + in[3:]
		case in == "/.":
			in = "/"
		case strings.HasPrefix(in, "/../"):
			in = "/" + in[4:]
			if i := strings.LastIndexByte(out, '/'); i >= 0 {
				out = out[:i]
			} else {
				out = ""
			}
		case in == "/..":
			in = "/"
			if i := strings.LastIndexByte(out, '/'); i >= 0 {
				out = out[:i]
			} else {
				out = ""
			}
		case in == "." || in == "..":
			in = ""
		default:
			start := 0
			if strings.HasPrefix(in, "/") {
				start = 1
			}
			if idx := strings.IndexByte(in[start:], '/'); idx < 0 {
				out += in
				in = ""
			} else {
				out += in[:start+idx]
				in = in[start+idx:]
			}
		}
	}
	return out
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= 0x80 {
			return false
		}
	}
	return true
}

// normalizeURLAttribute serializes an href/src value using the Web (WHATWG)
// URL serializer semantics: lowercase scheme + host, IDNA/punycode host, strip
// default ports, resolve dot-segments, preserve query and fragment.
func normalizeURLAttribute(raw string, base *url.URL) (string, error) {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil {
		return "", err
	}
	if base != nil {
		u = base.ResolveReference(u)
	}
	if !u.IsAbs() {
		return "", fmt.Errorf("URL must be absolute")
	}
	if u.Host == "" {
		// Opaque URL with no authority (mailto:, tel:, javascript:, data:,
		// about:, sms:, ...). The WHATWG URL parser accepts these; serialize
		// scheme + opaque remainder verbatim (scheme lowercased), matching
		// new URL().href. No host/port/dot-segment normalization applies.
		rest := u.Opaque
		if u.RawQuery != "" {
			rest += "?" + u.RawQuery
		}
		if u.Fragment != "" {
			rest += "#" + u.EscapedFragment()
		}
		return strings.ToLower(u.Scheme) + ":" + rest, nil
	}
	if u.User != nil {
		return "", fmt.Errorf("userinfo not allowed in signed URL")
	}
	u.Scheme = strings.ToLower(u.Scheme)
	host := strings.ToLower(u.Hostname())
	if !isASCII(host) {
		ascii, err := idna.Lookup.ToASCII(host)
		if err != nil {
			return "", fmt.Errorf("idna: %w", err)
		}
		host = ascii
	}
	port := u.Port()
	if (u.Scheme == "https" && port == "443") || (u.Scheme == "http" && port == "80") {
		port = ""
	}
	if strings.Contains(host, ":") {
		host = "[" + strings.Trim(host, "[]") + "]"
	}
	if port != "" {
		host = net.JoinHostPort(strings.Trim(host, "[]"), port)
	}
	u.Host = host
	cleaned := removeDotSegments(u.EscapedPath())
	if cleaned == "" {
		cleaned = "/"
	}
	u.RawPath = cleaned
	if unesc, err := url.PathUnescape(cleaned); err == nil {
		u.Path = unesc
	} else {
		u.Path = cleaned
	}
	return u.String(), nil
}
