package canonicalize

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	whatwgurl "github.com/nlnwa/whatwg-url/url"
	htmlpkg "golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

const (
	maxResourceBytes   = 1024 * 1024
	maxClaims          = 64
	maxClaimFieldBytes = 4096
	maxElementDepth    = 256
)

// Boundary-producing elements from the protocol draft. A boundary-producing
// element emits a line feed after its descendants have contributed text.
const blockElements = `address|article|aside|blockquote|details|dialog|div|dl|` +
	`fieldset|figcaption|figure|footer|form|h[1-6]|header|hgroup|hr|li|main|nav|` +
	`ol|p|pre|section|table|td|th|tr|ul`

var (
	attrBodyRE  = regexp.MustCompile(`(?i)^</?\s*[a-z][a-z0-9-]*`)
	attrRE      = regexp.MustCompile("([^\\s\"'<>/=]+)(?:\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s\"'=<>`]+)))?")
	blockNameRE = regexp.MustCompile(`(?i)^(` + blockElements + `)$`)
)

var signedAttrs = []string{"href", "src", "alt", "aria-label"}

var voidTags = map[string]bool{
	"area": true, "base": true, "br": true, "col": true, "embed": true,
	"hr": true, "img": true, "input": true, "link": true, "meta": true,
	"param": true, "source": true, "track": true, "wbr": true,
}

var excludedTags = map[string]bool{
	"script": true, "style": true, "template": true, "noscript": true,
	"iframe": true, "head": true, "meta": true, "link": true,
}

// namedEntities (the full HTML5 named-reference table) is defined in
// entities_gen.go, generated by tools/gen-entities.py. Lookups are
// case-sensitive per the HTML Living Standard.

var (
	namedEntityRE        = regexp.MustCompile(`&[a-zA-Z][a-zA-Z0-9]*;`)
	unterminatedEntityRE = regexp.MustCompile(`&[a-zA-Z][a-zA-Z0-9]*(?:$|[^a-zA-Z0-9;])`)
)

// ExtractCanonicalText extracts canonical content from an HTML fragment for
// signing or verification. Mirrors the JS extractCanonicalText() reference
// implementation: strips excluded elements, emits signed semantic attribute
// records for href/src/alt/aria-label, converts boundary-producing elements
// to line feeds, decodes entities, and runs the full text normalization
// pipeline. The returned string is trimmed.
func ExtractCanonicalText(html string, opts ...Options) (string, error) {
	if len(html) > maxResourceBytes || !utf8.ValidString(html) {
		return "", fmt.Errorf("resource-limit-exceeded")
	}
	var o Options
	if len(opts) > 0 {
		o = opts[0]
	}
	base, err := parseBaseURL(o.BaseURL)
	if err != nil {
		return "", err
	}

	if err := validatePortableHTML(html); err != nil {
		return "", err
	}
	fragment, err := htmlpkg.ParseFragment(strings.NewReader(html), &htmlpkg.Node{Type: htmlpkg.ElementNode, Data: "div", DataAtom: atom.Div})
	if err != nil {
		return "", fmt.Errorf("parser-profile-unsupported: %v", err)
	}
	var parts []string
	if err := walkHTMLNodes(fragment, &parts, base, o); err != nil {
		return "", err
	}
	result := finalizeCanonicalParts(parts)
	if len(result) > maxResourceBytes {
		return "", fmt.Errorf("resource-limit-exceeded")
	}
	return result, nil
}

// ExtractClaimsFromSignedSection returns claim metadata from direct child meta
// elements. If the fragment contains a top-level signed-section, that element
// supplies the children; otherwise the fragment is treated as section inner HTML.
func ExtractClaimsFromSignedSection(source string) (map[string]string, error) {
	if len(source) > maxResourceBytes || !utf8.ValidString(source) {
		return nil, fmt.Errorf("resource-limit-exceeded")
	}
	if err := validatePortableHTML(source); err != nil {
		return nil, err
	}
	fragment, err := htmlpkg.ParseFragment(strings.NewReader(source), &htmlpkg.Node{Type: htmlpkg.ElementNode, Data: "div", DataAtom: atom.Div})
	if err != nil {
		return nil, fmt.Errorf("parser-profile-unsupported: %v", err)
	}
	children := fragment
	for _, node := range fragment {
		if node.Type == htmlpkg.ElementNode && strings.EqualFold(node.Data, "signed-section") {
			children = children[:0]
			for child := node.FirstChild; child != nil; child = child.NextSibling {
				children = append(children, child)
			}
			break
		}
	}
	claims := make(map[string]string)
	for _, node := range children {
		if node.Type != htmlpkg.ElementNode || !strings.EqualFold(node.Data, "meta") {
			continue
		}
		attrs := make(map[string]string, len(node.Attr))
		for _, attr := range node.Attr {
			attrs[strings.ToLower(attr.Key)] = attr.Val
		}
		rawName, hasName := attrs["name"]
		rawContent, hasContent := attrs["content"]
		if !hasName || !hasContent {
			return nil, fmt.Errorf("claim-malformed")
		}
		if len(claims) >= maxClaims {
			return nil, fmt.Errorf("resource-limit-exceeded")
		}
		name, err := NormalizeChecked(rawName)
		if err != nil {
			return nil, err
		}
		content, err := NormalizeChecked(rawContent)
		if err != nil {
			return nil, err
		}
		name = strings.TrimSpace(name)
		content = strings.TrimSpace(content)
		if name == "" {
			return nil, fmt.Errorf("claim-malformed")
		}
		if len([]byte(name)) > maxClaimFieldBytes || len([]byte(content)) > maxClaimFieldBytes {
			return nil, fmt.Errorf("resource-limit-exceeded")
		}
		if _, duplicate := claims[name]; duplicate {
			return nil, fmt.Errorf("claim-duplicate")
		}
		claims[name] = content
	}
	return claims, nil
}

// x/net/html repairs malformed input and does not expose parser diagnostics.
// Keep a strict source preflight so repaired trees cannot enter the portable
// profile silently.
func validatePortableHTML(source string) error {
	stack := []string{}
	t := htmlpkg.NewTokenizer(strings.NewReader(source))
	for {
		tt := t.Next()
		if tt == htmlpkg.ErrorToken {
			break
		}
		switch tt {
		case htmlpkg.StartTagToken, htmlpkg.SelfClosingTagToken:
			if err := validatePortableReferences(string(t.Raw())); err != nil {
				return err
			}
			if err := validateDuplicateAttributes(string(t.Raw())); err != nil {
				return err
			}
			nameBytes, more := t.TagName()
			name := strings.ToLower(string(nameBytes))
			if name == "svg" || name == "math" || name == "foreignobject" {
				return fmt.Errorf("parser-profile-unsupported")
			}
			seen := map[string]bool{}
			for more {
				keyBytes, _, next := t.TagAttr()
				key := strings.ToLower(string(keyBytes))
				if seen[key] {
					return fmt.Errorf("parser-profile-unsupported")
				}
				seen[key] = true
				more = next
			}
			if tt == htmlpkg.StartTagToken && !voidTags[name] {
				if len(stack) >= maxElementDepth {
					return fmt.Errorf("resource-limit-exceeded")
				}
				stack = append(stack, name)
			}
		case htmlpkg.EndTagToken:
			nameBytes, _ := t.TagName()
			name := strings.ToLower(string(nameBytes))
			if len(stack) == 0 || stack[len(stack)-1] != name {
				return fmt.Errorf("parser-profile-unsupported")
			}
			stack = stack[:len(stack)-1]
		case htmlpkg.TextToken:
			rawText := len(stack) > 0 && (stack[len(stack)-1] == "script" || stack[len(stack)-1] == "style" || stack[len(stack)-1] == "iframe")
			if !rawText {
				if err := validatePortableReferences(string(t.Raw())); err != nil {
					return err
				}
			}
			if len(stack) > 0 && stack[len(stack)-1] == "table" && strings.TrimSpace(string(t.Raw())) != "" {
				return fmt.Errorf("parser-profile-unsupported")
			}
		case htmlpkg.CommentToken:
			raw := string(t.Raw())
			if !strings.HasPrefix(raw, "<!--") || !strings.HasSuffix(raw, "-->") {
				return fmt.Errorf("parser-profile-unsupported")
			}
			body := raw[4 : len(raw)-3]
			if strings.Contains(body, "--") || strings.HasSuffix(body, "-") {
				return fmt.Errorf("parser-profile-unsupported")
			}
		case htmlpkg.DoctypeToken:
			return fmt.Errorf("parser-profile-unsupported")
		}
	}
	if len(stack) != 0 {
		return fmt.Errorf("parser-profile-unsupported: unclosed %v", stack)
	}
	return nil
}

func validatePortableReferences(source string) error {
	if unterminatedEntityRE.MatchString(source) || hasUnterminatedNumericReference(source) {
		return fmt.Errorf("parser-profile-unsupported")
	}
	for _, loc := range namedEntityRE.FindAllStringIndex(source, -1) {
		if _, ok := namedEntities[source[loc[0]:loc[1]]]; !ok {
			return fmt.Errorf("parser-profile-unsupported: entity %s", source[loc[0]:loc[1]])
		}
	}
	return nil
}

func hasUnterminatedNumericReference(source string) bool {
	for i := 0; i+2 < len(source); i++ {
		if source[i] != '&' || source[i+1] != '#' {
			continue
		}
		j := i + 2
		if j < len(source) && (source[j] == 'x' || source[j] == 'X') {
			j++
			start := j
			for j < len(source) && ((source[j] >= '0' && source[j] <= '9') ||
				(source[j] >= 'a' && source[j] <= 'f') || (source[j] >= 'A' && source[j] <= 'F')) {
				j++
			}
			if j == start {
				continue
			}
		} else {
			start := j
			for j < len(source) && source[j] >= '0' && source[j] <= '9' {
				j++
			}
			if j == start {
				continue
			}
		}
		if j >= len(source) || source[j] != ';' {
			return true
		}
	}
	return false
}

func validateDuplicateAttributes(token string) error {
	body := attrBodyRE.ReplaceAllString(token, "")
	body = strings.TrimSuffix(strings.TrimSpace(body), ">")
	body = strings.TrimSuffix(strings.TrimSpace(body), "/")
	seen := map[string]bool{}
	for _, match := range attrRE.FindAllStringSubmatch(body, -1) {
		name := strings.ToLower(match[1])
		if seen[name] {
			return fmt.Errorf("parser-profile-unsupported")
		}
		seen[name] = true
	}
	return nil
}

func walkHTMLNodes(nodes []*htmlpkg.Node, parts *[]string, base *whatwgurl.Url, o Options) error {
	for _, node := range nodes {
		switch node.Type {
		case htmlpkg.TextNode:
			normalized, err := NormalizeTextChecked(node.Data, o)
			if err != nil {
				return err
			}
			appendCanonicalPart(parts, strings.ReplaceAll(normalized, "@", "@@"))
		case htmlpkg.CommentNode, htmlpkg.DoctypeNode:
			continue
		case htmlpkg.ElementNode:
			name := strings.ToLower(node.Data)
			if excludedTags[name] {
				continue
			}
			attrs := make(map[string]string, len(node.Attr))
			for _, attr := range node.Attr {
				attrs[strings.ToLower(attr.Key)] = attr.Val
			}
			if err := appendAttributeRecords(parts, name, attrs, base); err != nil {
				return err
			}
			if name == "br" {
				appendCanonicalPart(parts, "\n")
			} else {
				children := make([]*htmlpkg.Node, 0)
				for child := node.FirstChild; child != nil; child = child.NextSibling {
					children = append(children, child)
				}
				if err := walkHTMLNodes(children, parts, base, o); err != nil {
					return err
				}
				if blockNameRE.MatchString(name) || name == "signed-section" {
					appendCanonicalPart(parts, "\n")
				}
			}
		}
	}
	return nil
}

// CanonicalizeClaims serializes a claims map as sorted "name:content\n"
// records. Both names and values are pushed through NormalizeText before
// serialization so the output is independent of trivial Unicode noise.
// It returns an error for the profile's MUST-fail conditions: an empty
// normalized name is "claim-malformed", and two names that normalize to the
// same value are "claim-duplicate". Names are sorted by UTF-8 bytes.
func CanonicalizeClaims(claims map[string]string) (string, error) {
	if len(claims) > maxClaims {
		return "", fmt.Errorf("resource-limit-exceeded")
	}
	type entry struct{ name, value string }
	entries := make([]entry, 0, len(claims))
	seen := make(map[string]bool, len(claims))
	for k, v := range claims {
		name, err := NormalizeChecked(k)
		if err != nil {
			return "", err
		}
		value, err := NormalizeChecked(v)
		if err != nil {
			return "", err
		}
		name = strings.TrimSpace(name)
		value = strings.TrimSpace(value)
		if name == "" {
			return "", fmt.Errorf("claim-malformed")
		}
		if seen[name] {
			return "", fmt.Errorf("claim-duplicate")
		}
		if len([]byte(name)) > maxClaimFieldBytes || len([]byte(value)) > maxClaimFieldBytes {
			return "", fmt.Errorf("resource-limit-exceeded")
		}
		seen[name] = true
		entries = append(entries, entry{name, value})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].name < entries[j].name
	})
	var b strings.Builder
	for _, e := range entries {
		b.WriteString(escapeClaimField(e.name))
		b.WriteByte(':')
		b.WriteString(escapeClaimField(e.value))
		b.WriteByte('\n')
	}
	result := b.String()
	if len(result) > maxResourceBytes {
		return "", fmt.Errorf("resource-limit-exceeded")
	}
	return result, nil
}

// CanonicalizeClaimsStrict is retained as a compatibility alias. Both public
// entry points enforce the same fail-closed profile.
func CanonicalizeClaimsStrict(claims map[string]string) (string, error) {
	return CanonicalizeClaims(claims)
}

func escapeClaimField(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, ":", `\:`)
	return strings.ReplaceAll(value, "\n", `\n`)
}

func appendCanonicalPart(parts *[]string, value string) {
	if value == "" {
		return
	}
	*parts = append(*parts, value)
}

func finalizeCanonicalParts(parts []string) string {
	text := strings.Join(parts, "")
	for strings.Contains(text, "  ") {
		text = strings.ReplaceAll(text, "  ", " ")
	}
	text = regexp.MustCompile(`[ \t]*\n[ \t]*`).ReplaceAllString(text, "\n")
	for strings.Contains(text, "\n\n") {
		text = strings.ReplaceAll(text, "\n\n", "\n")
	}
	return strings.Trim(text, " \n")
}

func appendAttributeRecords(parts *[]string, elementName string, attrs map[string]string, base *whatwgurl.Url) error {
	for _, attrName := range signedAttrs {
		raw, ok := attrs[attrName]
		if !ok {
			continue
		}
		value := raw
		if attrName == "href" || attrName == "src" {
			normalized, err := normalizeURLAttribute(value, base)
			if err != nil {
				if strings.Contains(err.Error(), "url-policy-violation") {
					return err
				}
				return fmt.Errorf("attribute-canonicalization-failed: %s.%s: %w", elementName, attrName, err)
			}
			value = normalized
		} else {
			normalized, err := NormalizeTextChecked(value)
			if err != nil {
				return fmt.Errorf("attribute-canonicalization-failed: %s.%s: %w", elementName, attrName, err)
			}
			value = strings.TrimSpace(normalized)
		}
		value = strings.ReplaceAll(value, "@", "@@")
		if strings.ContainsRune(value, '\n') {
			return fmt.Errorf("attribute-canonicalization-failed: %s.%s contains newline", elementName, attrName)
		}
		if len(*parts) > 0 {
			last := (*parts)[len(*parts)-1]
			if last != "" && !strings.HasSuffix(last, " ") && !strings.HasSuffix(last, "\n") {
				*parts = append(*parts, "\n")
			}
		}
		*parts = append(*parts, "@attr:"+elementName+":"+attrName+":"+value+"\n")
	}
	return nil
}

func parseBaseURL(raw string) (*whatwgurl.Url, error) {
	if raw == "" {
		return nil, nil
	}
	base, err := whatwgurl.Parse(raw)
	if err != nil {
		return nil, fmt.Errorf("attribute-canonicalization-failed: %w", err)
	}
	if base.Scheme() != "https" || base.Hostname() == "" || base.Username() != "" || base.Password() != "" {
		return nil, fmt.Errorf("url-policy-violation")
	}
	return base, nil
}

// normalizeURLAttribute parses and serializes an href/src with the WHATWG URL algorithm.
func normalizeURLAttribute(raw string, base *whatwgurl.Url) (string, error) {
	for _, r := range raw {
		if r <= 0x1f || r == 0x7f {
			return "", fmt.Errorf("url-policy-violation")
		}
	}
	var u *whatwgurl.Url
	var err error
	if base != nil {
		u, err = base.Parse(raw)
	} else {
		u, err = whatwgurl.Parse(raw)
	}
	if err != nil {
		return "", err
	}
	if u.Scheme() != "https" || u.Username() != "" || u.Password() != "" {
		return "", fmt.Errorf("url-policy-violation")
	}
	if u.Hostname() == "" {
		return "", fmt.Errorf("attribute-canonicalization-failed")
	}
	return u.Href(false), nil
}
