#!/usr/bin/env python3
"""Generate the shared HTML5 named-entity tables for the regex-based bindings
(JavaScript, PHP) from the Python stdlib's authoritative html5 map.

Source of truth: data/html5-entities.json (this script regenerates it and the
per-language source files). Only semicolon-terminated references are emitted;
per draft §4.1 character references in signed content are semicolon-terminated,
and this keeps the regex-based decoders byte-identical to the real-parser
bindings (Python/Rust/Go) for well-formed input.
"""
import html.entities as he
import json, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
ents = {f"&{k}": v for k, v in sorted(he.html5.items()) if k.endswith(";")}

# 1) JSON source of truth
(root / "data" / "html5-entities.json").write_text(
    json.dumps(ents, ensure_ascii=False, indent=0, sort_keys=True) + "\n",
    encoding="utf-8",
)

# 2) JavaScript module
js = ["// GENERATED by tools/gen-entities.py -- do not edit by hand.",
      "// Full HTML5 named character references (semicolon-terminated).",
      "export const NAMED_ENTITIES = {"]
for k, v in ents.items():
    js.append(f"  {json.dumps(k)}: {json.dumps(v)},")
js.append("};")
(root / "javascript" / "entities.js").write_text("\n".join(js) + "\n", encoding="utf-8")

# 3) PHP file
php = ["<?php", "// GENERATED by tools/gen-entities.py -- do not edit by hand.",
       "// Full HTML5 named character references (semicolon-terminated).",
       "namespace HTMLTrust\\Canonicalization;", "", "final class Entities", "{",
       "    /** @var array<string,string> */", "    public const NAMED = ["]
for k, v in ents.items():
    ky = k.replace("\\", "\\\\").replace("'", "\\'")
    vv = v.replace("\\", "\\\\").replace("'", "\\'")
    php.append(f"        '{ky}' => '{vv}',")
php += ["    ];", "}", ""]
(root / "php" / "src" / "Entities.php").write_text("\n".join(php), encoding="utf-8")

# 4) Go source
def go_quote(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'

go = ["// Code generated by tools/gen-entities.py; DO NOT EDIT.",
      "// Full HTML5 named character references (semicolon-terminated).",
      "package canonicalize", "",
      "var namedEntities = map[string]string{"]
for k, v in ents.items():
    go.append(f"\t{go_quote(k)}: {go_quote(v)},")
go += ["}", ""]
(root / "go" / "entities_gen.go").write_text("\n".join(go), encoding="utf-8")

print("wrote:")
print("  data/html5-entities.json   ", len(ents), "entities")
print("  javascript/entities.js")
print("  php/src/Entities.php")
print("  go/entities_gen.go")
